# Copyright 2021 Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

name: Proofs

on:
  push:
    branches:
      - master
      - rt
  # this action needs access to secrets.
  # The actual test runs in a no-privilege VM, so it's Ok to run on untrusted PRs.
  pull_request_target:

jobs:
  all:
    name: All
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: ARM
            session: Lib SimplExportAndRefine
          - arch: ARM_HYP
            session: Lib
          - arch: RISCV64
            session: Lib SimplExportAndRefine
          - arch: X64
            session: Lib
    steps:
    - run: printenv
    - name: Proofs
      uses: seL4/ci-actions/aws-proofs@aws-ssh
      with:
        L4V_ARCH: ${{ matrix.arch }}
        isa_branch: ts-2020
        session: ${{ matrix.session }}
      env:
        GH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SSH: ${{ secrets.AWS_SSH }}
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: logs-${{ matrix.arch }}
        path: logs.tar.xz
