# Copyright 2021 Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

name: Proofs

on:
  push:
    branches:
      - master
      - rt
  pull_request_target:

jobs:
  aspec:
    name: All
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ARM]
    steps:
    - name: Proofs
      uses: seL4/ci-actions/aws-proofs@aws-proofs
      with:
        L4V_ARCH: ${{ matrix.arch }}
        isa_branch: ts-2020
        session: ASpec
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SSH: ${{ secrets.AWS_SSH }}
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: logs-${{ matrix.arch }}
        path: logs.tar.xz
